import json

resource_data = {
    "tenant_id": "1020",
    "instance_id": "admin@nskloudless.onmicrosoft.com",
    "app_id": "office365",
    "app_suite": "office365",
    "app_category": "SAAS apps",
    "creation_time": 1624849214,
    "modified_time": 1624849214,
    "resouce_category": "Security",
    "resource_subtype": "Policy",
    "resource_type": "OrganizationConfig",
    "resource_id": "OrganizationConfig",
    "metadata": {
        "PSComputerName": "outlook.office365.com",
        "RunspaceId": "bf2d7cc5-dd8d-421b-aba3-e5a5798f8f64",
        "PSShowComputerName": True,
        "OrganizationId": "NAMPR10A005.PROD.OUTLOOK.COM/Microsoft Exchange Hosted Organizations/nsengeco.onmicrosoft.com - NAMPR10A005.PROD.OUTLOOK.COM/ConfigurationUnits/nsengeco.onmicrosoft.com/Configuration",
        "Name": "nsengeco.onmicrosoft.com",
        "Identity": "nsengeco.onmicrosoft.com",
        "Guid": "f484a69b-d3d2-440c-8e91-efc2702dd5b5",
        "ObjectVersion": 16500,
        "DefaultPublicFolderAgeLimit": None,
        "DefaultPublicFolderIssueWarningQuota": "1.7 GB (1,825,361,920 bytes)",
        "DefaultPublicFolderProhibitPostQuota": "2 GB (2,147,483,648 bytes)",
        "DefaultPublicFolderMaxItemSize": "Unlimited",
        "DefaultPublicFolderDeletedItemRetention": "30.00:00:00",
        "DefaultPublicFolderMovedItemRetention": "7.00:00:00",
        "PublicFoldersLockedForMigration": False,
        "PublicFolderMigrationComplete": False,
        "PublicFolderMailboxesLockedForNewConnections": False,
        "PublicFolderMailboxesMigrationComplete": False,
        "PublicFolderShowClientControl": False,
        "PublicFoldersEnabled": "Local",
        "ActivityBasedAuthenticationTimeoutEnabled": True,
        "ActivityBasedAuthenticationTimeoutInterval": "06:00:00",
        "ActivityBasedAuthenticationTimeoutWithSingleSignOnEnabled": True,
        "AppsForOfficeEnabled": True,
        "AppsForOfficeCorpCatalogAppsCount": 0,
        "PrivateCatalogAppsCount": 0,
        "AVAuthenticationService": None,
        "CustomerFeedbackEnabled": None,
        "DistributionGroupDefaultOU": None,
        "DistributionGroupNameBlockedWordsList": [],
        "DistributionGroupNamingPolicy": "",
        "EwsAllowEntourage": None,
        "EwsAllowList": None,
        "EwsAllowMacOutlook": None,
        "EwsAllowOutlook": None,
        "AllowPlusAddressInRecipients": True,
        "MaskClientIpInReceivedHeadersEnabled": True,
        "EwsApplicationAccessPolicy": None,
        "EwsBlockList": None,
        "AutodiscoverPartialDirSync": False,
        "EwsEnabled": None,
        "IPListBlocked": [],
        "ElcProcessingDisabled": False,
        "AutoExpandingArchiveEnabled": False,
        "ComplianceMLBgdCrawlEnabled": False,
        "ExchangeNotificationEnabled": True,
        "ExchangeNotificationRecipients": [],
        "HierarchicalAddressBookRoot": None,
        "Industry": "NotSpecified",
        "MailTipsAllTipsEnabled": True,
        "MailTipsExternalRecipientsTipsEnabled": False,
        "MailTipsGroupMetricsEnabled": True,
        "MailTipsLargeAudienceThreshold": 25,
        "MailTipsMailboxSourcedTipsEnabled": True,
        "ManagedFolderHomepage": "",
        "MicrosoftExchangeRecipientEmailAddresses": [
            "SMTP:MicrosoftExchange329e71ec88ae4615bbc36ab6ce41109e@nsengeco.onmicrosoft.com"
        ],
        "MicrosoftExchangeRecipientEmailAddressPolicyEnabled": False,
        "MicrosoftExchangeRecipientPrimarySmtpAddress": "MicrosoftExchange329e71ec88ae4615bbc36ab6ce41109e@nsengeco.onmicrosoft.com",
        "MicrosoftExchangeRecipientReplyRecipient": None,
        "ForwardSyncLiveIdBusinessInstance": False,
        "OrganizationSummary": [],
        "ReadTrackingEnabled": False,
        "SCLJunkThreshold": 4,
        "SIPAccessService": None,
        "SIPSessionBorderController": None,
        "MaxConcurrentMigrations": "Unlimited",
        "MaxAddressBookPolicies": None,
        "MaxOfflineAddressBooks": None,
        "MaxInformationBarrierSegments": None,
        "MaxIBSegments": 5000,
        "MaxIBBridges": 5000,
        "IsExcludedFromOnboardMigration": False,
        "IsExcludedFromOffboardMigration": False,
        "IsFfoMigrationInProgress": False,
        "ExternalCloudAccessEnabled": False,
        "IsProcessEhaMigratedMessagesEnabled": False,
        "TenantRelocationsAllowed": False,
        "ACLableSyncedObjectEnabled": False,
        "PreferredInternetCodePageForShiftJis": 0,
        "RequiredCharsetCoverage": 100,
        "ByteEncoderTypeFor7BitCharsets": 0,
        "PublicComputersDetectionEnabled": False,
        "RmsoSubscriptionStatus": "Unknown",
        "IntuneManagedStatus": True,
        "AzurePremiumSubscriptionStatus": False,
        "HybridConfigurationStatus": "Unknown",
        "ReleaseTrack": None,
        "CompassEnabled": None,
        "SharePointUrl": "https://nsengeco.sharepoint.com/",
        "MapiHttpEnabled": False,
        "RealTimeLogServiceEnabled": False,
        "CustomerLockboxEnabled": False,
        "OAuth2ClientProfileEnabled": True,
        "PerTenantSwitchToESTSEnabled": False,
        "LinkPreviewEnabled": True,
        "OutlookPayEnabled": True,
        "ConnectorsEnabled": True,
        "ConnectorsActionableMessagesEnabled": True,
        "SmtpActionableMessagesEnabled": True,
        "OfficeGraphActivitySharingOrgOptout": False,
        "UnblockUnsafeSenderPromptEnabled": True,
        "AsyncSendEnabled": True,
        "RefreshSessionEnabled": False,
        "IsAgendaMailEnabled": True,
        "NetworkThrottlingConfiguration": None,
        "BookingsEnabled": True,
        "BookingsEnabledLastUpdateTime": "0001-01-01T00:00:00",
        "BookingsPaymentsEnabled": False,
        "BookingsSocialSharingRestricted": False,
        "BookingsAddressEntryRestricted": False,
        "BookingsAuthEnabled": False,
        "BookingsCreationOfCustomQuestionsRestricted": False,
        "BookingsExposureOfStaffDetailsRestricted": False,
        "BookingsNotesEntryRestricted": False,
        "BookingsPhoneNumberEntryRestricted": False,
        "BookingsMembershipApprovalRequired": False,
        "LeanPopoutEnabled": False,
        "OutlookMobileHelpShiftEnabled": True,
        "OutlookMobileSingleAccountEnabled": False,
        "OutlookMobileGCCRestrictionsEnabled": False,
        "ElevatedAccessControl": None,
        "AuditDisabled": False,
        "WebPushNotificationsDisabled": False,
        "WebSuggestedRepliesDisabled": False,
        "ConnectorsEnabledForOutlook": True,
        "ConnectorsEnabledForOutlookLastUpdateTime": "0001-01-01T00:00:00",
        "ConnectorsEnabledForTeams": True,
        "ConnectorsEnabledForTeamsLastUpdateTime": "0001-01-01T00:00:00",
        "ConnectorsEnabledForSharepoint": True,
        "ConnectorsEnabledForSharepointLastUpdateTime": "0001-01-01T00:00:00",
        "ConnectorsEnabledForYammer": True,
        "ConnectorsEnabledForYammerLastUpdateTime": "0001-01-01T00:00:00",
        "AutoEnableArchiveMailbox": False,
        "OnlineMeetingsByDefaultEnabled": False,
        "SendFromAliasEnabled": False,
        "OutlookTextPredictionDisabled": False,
        "MobileAppEducationEnabled": True,
        "EnableForwardingAddressSyncForMailboxes": False,
        "OutlookGifPickerDisabled": False,
        "WorkspaceTenantEnabled": True,
        "BasicAuthBlockedApps": "None",
        "ShortenEventScopeDefault": "None",
        "DefaultMinutesToReduceShortEventsBy": 5,
        "DefaultMinutesToReduceLongEventsBy": 10,
        "FindTimeAttendeeAuthenticationEnabled": False,
        "FindTimeOnlineMeetingOptionDisabled": False,
        "FindTimeAutoScheduleDisabled": False,
        "MessageRemindersEnabled": True,
        "IsEopTrialEnabled": False,
        "EnableOutlookEvents": False,
        "IsComplianceTrialEnabled": False,
        "MessageHighlightsEnabled": True,
        "OrganizationConfigHash": "fZDPSsQwEMZfpfSkB9OkrIKQzbK0iF7Ug3qP6TQEmpmSpIvrq3nwkXwFU3tRKXuafx/fb2a+Pj7l7s0PxQFCdITbUjBeFoCGOod2W06pvxBX5U7Jtrk9vgbXNYS9s1PQKeuVvIutTroBTBDUU5hAVn9act95h62L46CPLwtFcVbz4kxc5sA2tbhmdX0uqzVl9n8ebdDzNg/BanTvC/hGD/GHtT6WjwEOjqa4jhczfsPmhDOe2afkcm8MjAm6lrx2uV7ivfagMAJaMMQIvTOBIvWJGfKy+iXKp/1zqNa/+Q0=",
        "LegacyExchangeDN": "/o=ExchangeLabs/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=nsengeco.onmicrosoft.com/cn=Configuration",
        "DisplayName": "nsengeco",
        "Heuristics": "None",
        "ResourceAddressLists": [
            "\\All Rooms"
        ],
        "IsMixedMode": True,
        "PreviousAdminDisplayVersion": "0.10 (14.0.100.0)",
        "IsAddressListPagingEnabled": True,
        "ForeignForestFQDN": [],
        "ForeignForestOrgAdminUSGSid": None,
        "ForeignForestRecipientAdminUSGSid": None,
        "ForeignForestViewOnlyAdminUSGSid": None,
        "MimeTypes": [],
        "IsLicensingEnforced": True,
        "IsTenantAccessBlocked": False,
        "IsDualWriteEnabled": True,
        "IsTenantInGracePeriod": False,
        "IsDehydrated": False,
        "IsGuidPrefixedLegacyDnDisabled": False,
        "IsMailboxForcedReplicationDisabled": False,
        "RBACConfigurationVersion": "0.1 (15.20.4219.22)",
        "RootPublicFolderMailbox": {
            "IsValid": False,
            "CanUpdate": True,
            "HierarchyMailboxGuid": "00000000-0000-0000-0000-000000000000",
            "LockedForMigration": False
        },
        "RemotePublicFolderMailboxes": [],
        "AdminDisplayVersion": "0.20 (15.20.4219.22)",
        "IsUpgradingOrganization": False,
        "IsUpdatingServicePlan": False,
        "ServicePlan": "BPOS_S_E15_0",
        "TargetServicePlan": "",
        "WACDiscoveryEndpoint": "",
        "UMAvailableLanguages": [
            "en-US"
        ],
        "AdfsAuthenticationConfiguration": "",
        "AdfsIssuer": None,
        "AdfsAudienceUris": [],
        "AdfsSignCertificateThumbprints": [],
        "AdfsEncryptCertificateThumbprint": None,
        "SiteMailboxCreationURL": None,
        "DefaultDataEncryptionPolicy": None,
        "MailboxDataEncryptionEnabled": False,
        "DefaultAuthenticationPolicy": None,
        "AllowedMailboxRegions": [
            "nam=namprd10.prod.outlook.com"
        ],
        "DefaultMailboxRegion": "nam",
        "IsJitEnabled": None,
        "AutoJitForests": None,
        "DefaultMailboxRegionLastUpdateTime": "2021-03-21T22:12:13.4713829Z",
        "AllowedMailboxRegionsLastUpdateTime": "2021-03-21T22:12:13Z",
        "DirectReportsGroupAutoCreationEnabled": False,
        "AllowToAddGuests": True,
        "GuestsEnabled": True,
        "GroupsCreationEnabled": True,
        "HiddenMembershipGroupsCreationEnabled": False,
        "GroupsCreationWhitelistedId": None,
        "GroupsUsageGuidelinesLink": None,
        "DefaultGroupAccessType": "Private",
        "GroupLifeCyclePolicy": "<GroupLifeCyclePolicy><GroupLifetimeInDays>-1</GroupLifetimeInDays><ManagedGroupType p2:nil=\"True\" xmlns:p2=\"http://www.w3.org/2001/XMLSchema-instance\" /><LastUpdatedTime>2021-06-10T23:39:17.7886591Z</LastUpdatedTime></GroupLifeCyclePolicy>",
        "GroupsNamingPolicy": None,
        "DataClassifications": "<DataClassifications />",
        "VisibleMeetingUpdateProperties": "Location,AllProperties:15",
        "MatchSenderOrganizerProperties": False,
        "DisableMailboxForSubstrateOnlyFinished": False,
        "InPlaceHolds": [],
        "ServiceInstanceMove": None,
        "GuestsUsageGuidelinesLink": None,
        "OrganizationPrivacyStatementLink": None,
        "IsMIPLabelForGroupsEnabled": False,
        "IsGroupFoldersAndRulesEnabled": False,
        "BlockMoveMessagesForGroupFolders": False,
        "FocusedInboxOn": None,
        "FocusedInboxOnLastUpdateTime": "0001-01-01T00:00:00",
        "ForestConfigVersion": "",
        "ForestConfigLastRunTime": "0001-01-01T00:00:00",
        "EndUserDLUpgradeFlowsDisabled": False,
        "OcmGroupId": None,
        "Id": "First Organization",
        "IsValid": True,
        "ExchangeVersion": "0.1 (8.0.535.0)",
        "DistinguishedName": "CN=Configuration,CN=nsengeco.onmicrosoft.com,CN=ConfigurationUnits,DC=NAMPR10A005,DC=PROD,DC=OUTLOOK,DC=COM",
        "ObjectCategory": "NAMPR10A005.PROD.OUTLOOK.COM/Configuration/Schema/ms-Exch-Configuration-Unit-Container",
        "ObjectClass": [
            "top",
            "container",
            "msExchOrganizationContainer",
            "msExchConfigurationUnitContainer"
        ],
        "WhenChanged": "2021-06-10T23:39:34+00:00",
        "WhenCreated": "2021-03-21T22:11:56+00:00",
        "WhenChangedUTC": "2021-06-10T23:39:34Z",
        "WhenCreatedUTC": "2021-03-21T22:11:56Z",
        "ExchangeObjectId": "253ddaee-a40f-4689-8326-79a126683a30",
        "OriginatingServer": "MWHPR10A005DC02.NAMPR10A005.PROD.OUTLOOK.COM",
        "ObjectState": "Changed"
    }
}

if __name__ == '__main__':
    resource_binary = json.dumps(resource_data).encode('utf8')
    kb = len(resource_binary)/1024
    # Result: approximate 10 KB for a huge resource
    print(f"{kb} KB")
